name: CI

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  HAMMING_WITH_AVX2: OFF
  HAMMING_WITH_AVX512: OFF
  HAMMING_WITH_OPENMP: OFF

jobs:
  build-and-test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: enable openmp on linux
      run: echo "HAMMING_WITH_OPENMP=ON" >> $GITHUB_ENV
      if: runner.os == 'Linux'

    - name: make build directory
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: configure cmake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=ON -DHAMMING_BUILD_BENCHMARKS=ON -DHAMMING_WITH_SSE2=ON -DHAMMING_WITH_AVX2=$HAMMING_WITH_AVX2 -DHAMMING_WITH_AVX512=$HAMMING_WITH_AVX512 -DHAMMING_BUILD_PYTHON=ON -DHAMMING_WITH_OPENMP=$HAMMING_WITH_OPENMP

    - name: build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: run tests
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest

  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: set pyver for pre-commit cache
        run: echo "pyver=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.pyver }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-${{ env.pyver }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit script
        run: ./ci/pre-commit.sh
      - name: Commit any changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix code formatting
