name: Build Wheels + PyPI deploy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_TEST_REQUIRES: "pytest numpy"
      CIBW_TEST_COMMAND: "pytest {project}/python/tests -v"
      CIBW_TEST_SKIP: "pp* *-musllinux*"
      CIBW_ENVIRONMENT: "BLAS=None LAPACK=None ATLAS=None"
      CIBW_SKIP: "*-manylinux_i686"
      CIBW_BUILD_VERBOSITY: 3

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: enable openmp on linux
        run: echo 'CIBW_ENVIRONMENT=HAMMING_WITH_OPENMP=ON' >> $GITHUB_ENV
        if: runner.os == 'Linux'

      - uses: pypa/cibuildwheel@v2.3.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build-wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
